import { randomUUID } from 'node:crypto'
import { relations } from 'drizzle-orm'
import {
  boolean,
  int,
  mysqlEnum,
  mysqlTable,
  smallint,
  text,
  timestamp,
  uniqueIndex,
  varchar,
} from 'drizzle-orm/mysql-core'

// UUID primary keys are generated by the application (MySQL has no
// gen_random_uuid()/uuid type). Stored as CHAR-like varchar(36).
const uuidPk = () =>
  varchar('id', { length: 36 })
    .primaryKey()
    .$defaultFn(() => randomUUID())

const fk = (name: string) => varchar(name, { length: 36 })

// ---- Schools ----
export const schools = mysqlTable('schools', {
  id: uuidPk(),
  name: text('name').notNull(),
  slug: varchar('slug', { length: 255 }).notNull().unique(),
  // Reserved for future email-domain based verification.
  domain: text('domain'),
  createdAt: timestamp('created_at', { mode: 'date' }).notNull().defaultNow(),
})

// ---- Users ----
export const users = mysqlTable('users', {
  id: uuidPk(),
  email: varchar('email', { length: 320 }).notNull().unique(),
  passwordHash: text('password_hash').notNull(),
  displayName: text('display_name').notNull(),
  role: mysqlEnum('role', ['student', 'admin']).notNull().default('student'),
  status: mysqlEnum('status', ['active', 'disabled']).notNull().default('active'),
  schoolId: fk('school_id').references(() => schools.id, {
    onDelete: 'set null',
  }),
  resetToken: varchar('reset_token', { length: 255 }),
  resetTokenExpiry: timestamp('reset_token_expiry', { mode: 'date' }),
  createdAt: timestamp('created_at', { mode: 'date' }).notNull().defaultNow(),
})

// ---- Invites (whitelist) ----
export const invites = mysqlTable('invites', {
  id: uuidPk(),
  email: varchar('email', { length: 320 }).notNull(),
  schoolId: fk('school_id')
    .notNull()
    .references(() => schools.id, { onDelete: 'cascade' }),
  token: varchar('token', { length: 255 }).notNull().unique(),
  status: mysqlEnum('status', ['pending', 'accepted', 'revoked'])
    .notNull()
    .default('pending'),
  invitedBy: fk('invited_by').references(() => users.id, {
    onDelete: 'set null',
  }),
  expiresAt: timestamp('expires_at', { mode: 'date' }).notNull(),
  createdAt: timestamp('created_at', { mode: 'date' }).notNull().defaultNow(),
})

// ---- Professors ----
export const professors = mysqlTable('professors', {
  id: uuidPk(),
  schoolId: fk('school_id')
    .notNull()
    .references(() => schools.id, { onDelete: 'cascade' }),
  firstName: varchar('first_name', { length: 255 }).notNull(),
  lastName: varchar('last_name', { length: 255 }).notNull(),
  department: varchar('department', { length: 255 }).notNull(),
  title: text('title'),
  createdAt: timestamp('created_at', { mode: 'date' }).notNull().defaultNow(),
})

// ---- Reviews ----
export const reviews = mysqlTable(
  'reviews',
  {
    id: uuidPk(),
    professorId: fk('professor_id')
      .notNull()
      .references(() => professors.id, { onDelete: 'cascade' }),
    authorId: fk('author_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    courseCode: text('course_code'),
    qualityRating: smallint('quality_rating').notNull(),
    difficultyRating: smallint('difficulty_rating').notNull(),
    wouldTakeAgain: boolean('would_take_again').notNull().default(false),
    grade: text('grade'),
    comment: text('comment').notNull(),
    status: mysqlEnum('status', ['pending', 'approved', 'rejected'])
      .notNull()
      .default('pending'),
    moderatedBy: fk('moderated_by').references(() => users.id, {
      onDelete: 'set null',
    }),
    moderatedAt: timestamp('moderated_at', { mode: 'date' }),
    // Soft-delete: a student can request deletion; an admin confirms it.
    // While requested, the review is hidden from the public listing.
    deletionRequested: boolean('deletion_requested').notNull().default(false),
    deletionRequestedAt: timestamp('deletion_requested_at', { mode: 'date' }),
    createdAt: timestamp('created_at', { mode: 'date' }).notNull().defaultNow(),
  },
  (table) => ({
    // A user may only review a given professor once (edit instead of re-adding).
    reviewAuthorUnique: uniqueIndex('review_author_unique').on(
      table.professorId,
      table.authorId,
    ),
  }),
)

// ---- Review tags (many-to-many flattened) ----
export const reviewTags = mysqlTable(
  'review_tags',
  {
    id: uuidPk(),
    reviewId: fk('review_id')
      .notNull()
      .references(() => reviews.id, { onDelete: 'cascade' }),
    tag: varchar('tag', { length: 255 }).notNull(),
  },
  (table) => ({
    reviewTagUnique: uniqueIndex('review_tag_unique').on(
      table.reviewId,
      table.tag,
    ),
  }),
)

// ---- Votes (helpfulness) ----
export const votes = mysqlTable(
  'votes',
  {
    id: uuidPk(),
    reviewId: fk('review_id')
      .notNull()
      .references(() => reviews.id, { onDelete: 'cascade' }),
    userId: fk('user_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    value: int('value').notNull(), // +1 or -1
  },
  (table) => ({
    voteUnique: uniqueIndex('vote_unique').on(table.reviewId, table.userId),
  }),
)

// ---- Relations ----
export const schoolsRelations = relations(schools, ({ many }) => ({
  users: many(users),
  professors: many(professors),
  invites: many(invites),
}))

export const usersRelations = relations(users, ({ one, many }) => ({
  school: one(schools, {
    fields: [users.schoolId],
    references: [schools.id],
  }),
  reviews: many(reviews),
}))

export const professorsRelations = relations(professors, ({ one, many }) => ({
  school: one(schools, {
    fields: [professors.schoolId],
    references: [schools.id],
  }),
  reviews: many(reviews),
}))

export const reviewsRelations = relations(reviews, ({ one, many }) => ({
  professor: one(professors, {
    fields: [reviews.professorId],
    references: [professors.id],
  }),
  author: one(users, {
    fields: [reviews.authorId],
    references: [users.id],
  }),
  tags: many(reviewTags),
  votes: many(votes),
}))

export const reviewTagsRelations = relations(reviewTags, ({ one }) => ({
  review: one(reviews, {
    fields: [reviewTags.reviewId],
    references: [reviews.id],
  }),
}))

export const votesRelations = relations(votes, ({ one }) => ({
  review: one(reviews, {
    fields: [votes.reviewId],
    references: [reviews.id],
  }),
  user: one(users, {
    fields: [votes.userId],
    references: [users.id],
  }),
}))

// ---- Inferred types ----
export type School = typeof schools.$inferSelect
export type User = typeof users.$inferSelect
export type Invite = typeof invites.$inferSelect
export type Professor = typeof professors.$inferSelect
export type Review = typeof reviews.$inferSelect
export type ReviewTag = typeof reviewTags.$inferSelect
export type Vote = typeof votes.$inferSelect
